[package]
name = "smallmap"
description = "Small byte-sized generic key-value map type"
keywords = ["map", "table", "small", "key", "value"]
repository = "https://git.flanchan.moe/flanchan/smallmap"
homepage= "https://git.flanchan.moe/flanchan/smallmap"
version = "1.0.0"
authors = ["Avril <flanchan@cumallover.me>"]
edition = "2018"
license = "MIT"

[dependencies]

[build-dependencies]
rustc_version = "0.2"
