[package]
name = "smallmap"
description = "Small byte-sized generic key-value map type"
keywords = ["map", "table", "small", "key", "value"]

version = "1.0.0"
authors = ["Avril <flanchan@cumallover.me>"]
edition = "2018"

[dependencies]

[build-dependencies]
rustc_version = "0.2"
